importScripts(
  "scripts/utils.js",
  "scripts/storage.js",
  "scripts/private/options.js",
  "scripts/private/allowlist.js",
  "scripts/private/blocker.js",
  "scripts/private/ui-bridge.js",
  "scripts/private/task-queue.js",
  "scripts/private/upgrade.js",
  "scripts/private/setup.js"
)
